#include *i S:\my dropbox\code\autohotkey\github\shorthand3\plugins\sh_winpad.ahk
#include *i S:\my dropbox\code\autohotkey\github\shorthand3\plugins\sh_winmove.ahk
#include *i S:\my dropbox\code\autohotkey\github\shorthand3\plugins\sh_windowcloser.ahk
#include *i S:\my dropbox\code\autohotkey\github\shorthand3\plugins\sh_QuickSearchforAutohotkey.ahk
#include *i S:\my dropbox\code\autohotkey\github\shorthand3\plugins\sh_ontop.ahk
#include *i S:\my dropbox\code\autohotkey\github\shorthand3\plugins\sh_npprun.ahk
#include *i S:\my dropbox\code\autohotkey\github\shorthand3\plugins\sh_new_folder.ahk
#include *i S:\my dropbox\code\autohotkey\github\shorthand3\plugins\sh_foilscreensaver.ahk
#include *i S:\my dropbox\code\autohotkey\github\shorthand3\plugins\sh_easydrag.ahk
